### PR TITLE
Update files for HV programming feature

### PR DESCRIPTION
**Pull request by Dlloydev**
This firmware was originally downloaded from here, then updated to add some new features; namely HV programming, target power-cycle, target current overload sensing and operating mode selection. Please see [Arduino Nano HV UPDI Programmer](https://github.com/Dlloydev/jtag2updi/wiki/Arduino-Nano-HV-UPDI-Programmer)

### CODE REVIEW

**Comment by SpenceKonde** [comment]
Oh god, this is going to be a shitshow.... gotta hand-merge the eltangas upstream and your changes and my changes.

**Comment by Dlloydev** [comment]
After merging Eltangas and your changes, the conflicting file list should shorten to jtag2updi.cpp, sys.cpp and sys.h (excluding README.md). At that point (if it would help) I could just make my repo match yours, then re-apply the HV changes and run some quick tests to ensure its fully functional.

**Comment by SpenceKonde** [comment]
I see that you just updated something related to this? Are you able to make this stuff bloody work? I can't seem to get things working reliably on all parts, period, with or without the HV stuff - and I have so many other things on my to-do list I haven't had a chance to work on it. Frankly the last time I was working on this was so traumatic I just don't want to touch it :-(

**Comment by Dlloydev** [comment]
Sorry to hear that ... I've sold 16 and needed to replace 1 (sold out right now but I have a few spares). There's no issues that I know of ... gosh, you must've got one of the first I've made (also my first time working with SMT components). Would be glad to send a replacement if needed.

I noticed that Eltangas had done some minor fixes, so yes, I took a clone of his repo and added the HV programming functions ... hence the large update. Tested the 3 PA0 modes using the Nano HV Programmer with targets ATtiny3216 and ATtiny412.

EDIT:
Note that you should connect the HVUPDI signal directly to PA0 (extra resistance might cause problems). Also, I suggest using the 5V pin on the 6-pin header for a better power source (you'll only loose auto power cycle feature).

No rush for this ... I understand your plans / schedule / workload are constantly evolving.

> should I either grab your version, or you amend your pull request to have all these changes, so I can just merge it, steam-rolling over all the misguided and ineffective fixes in my version, and be done with it?

I'm totally green at how to amend a pull request, but willing to give it a try if/when needed. As it stands now, my repo includes everything from Eltangas (source folder).

**Comment by SpenceKonde** [comment]
Oh no, I don't suspect any issue with your hardware, I'm referring to problems with my firmware. I swear I had tested the hell out of the timeout behavior, was totally sure it could never leave jtag2updi in a bad state! But, I swear, within 24 hours of the changes to jtag2updi finally getting merged, I could not make anything work as reliably as I was certain it was. And I just could not bear to work on it again!

**Comment by SpenceKonde** [comment]
Let me see what the state of the PR is....

**Comment by SpenceKonde** [comment]
MEEEEEERGGEEEEEE! (like the ads for that "surge" energy drink from the 90's)

**Pull request merged**
